/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package halallabirintus;

/**
 *
 * @author PalkovicsAlex(SZOFT_
 */
public class HalalLabirintus extends javax.swing.JFrame {

    /**
     * Creates new form halalLabirintus
     */
    public HalalLabirintus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnJatek = new javax.swing.JButton();
        btnCredit = new javax.swing.JButton();
        btnKilep = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Halál Labirintus");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Halál Labirintus");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 400, -1));

        btnJatek.setBackground(new java.awt.Color(255, 190, 124));
        btnJatek.setForeground(new java.awt.Color(51, 51, 51));
        btnJatek.setText("Játék");
        btnJatek.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnJatek.setBorderPainted(false);
        btnJatek.setFocusPainted(false);
        btnJatek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJatekActionPerformed(evt);
            }
        });
        getContentPane().add(btnJatek, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 160, 30));

        btnCredit.setBackground(new java.awt.Color(255, 190, 124));
        btnCredit.setForeground(new java.awt.Color(51, 51, 51));
        btnCredit.setText("Credits");
        btnCredit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCredit.setBorderPainted(false);
        btnCredit.setFocusPainted(false);
        btnCredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditActionPerformed(evt);
            }
        });
        getContentPane().add(btnCredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 160, 30));

        btnKilep.setBackground(new java.awt.Color(255, 190, 124));
        btnKilep.setForeground(new java.awt.Color(51, 51, 51));
        btnKilep.setText("Kilépés");
        btnKilep.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKilep.setBorderPainted(false);
        btnKilep.setFocusPainted(false);
        btnKilep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKilepActionPerformed(evt);
            }
        });
        getContentPane().add(btnKilep, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 160, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Kepek/labirintusHatter (1).jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 260));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKilepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKilepActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnKilepActionPerformed

    private void btnJatekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJatekActionPerformed
       new Bevezetes().setVisible(true);
       dispose();
    }//GEN-LAST:event_btnJatekActionPerformed

    private void btnCreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalalLabirintus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalalLabirintus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalalLabirintus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalalLabirintus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalalLabirintus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCredit;
    private javax.swing.JButton btnJatek;
    private javax.swing.JButton btnKilep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
